name: Fineract Client Build

on:
  push:
    branches: [ inkomoko ]

jobs:
  
  deploy:
    
    name: Deploy archive to ubuntu server
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Setup Node.js and Ruby
      uses: actions/setup-node@v3
      with:
        node-version: '16.13.1'
      
    
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
      with:
        ruby-version: '2.7'

    - name: Install Bower dependencies
      run: |
        npm install -g bower
        bower --allow-root install
    
    - name: Build and archive app package
      run: |
        npm install --legacy-peer-deps
        npm install -g grunt-cli
        bundle install
        grunt prod
        tar -czvf app.tar.gz dist/community-app

    - name: Copy file using SCP
      run: |
        HOST=${{ secrets.VM_HOST }}
        USER=${{ secrets.VM_USER_DEV }}
        SOURCE_FILE=app.tar.gz
        DESTINATION_DIR=/home/mifosdev/fineract_deployment/frontend
        echo "${{ secrets.VM_KEY }}" > key.pem
        chmod 400 key.pem
        scp -i key.pem -P ${{ secrets.VM_PORT_DEV }} -o StrictHostKeyChecking=no $SOURCE_FILE $USER@$HOST:$DESTINATION_DIR
    
    - name: Build image on server and deploy
      run: ssh -i key.pem -p ${{ secrets.VM_PORT_DEV }} -o StrictHostKeyChecking=no -l ${{ secrets.VM_USER_DEV }} ${{ secrets.VM_HOST }} '/home/mifosdev/fineract_deployment/frontend/deploy.sh'
